// <auto-generated />
using CommunicationAppApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunicationAppApi.Migrations
{
    [DbContext(typeof(RegistersContext))]
    partial class RegistersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Contacts", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Registersid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("last")
                        .HasColumnType("longtext");

                    b.Property<string>("lastdate")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("server")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Registersid");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Domain.Registers", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("Domain.Contacts", b =>
                {
                    b.HasOne("Domain.Registers", null)
                        .WithMany("contactsList")
                        .HasForeignKey("Registersid");
                });

            modelBuilder.Entity("Domain.Registers", b =>
                {
                    b.Navigation("contactsList");
                });
#pragma warning restore 612, 618
        }
    }
}
